version: "3.3"

services:
  ftpd:
    image: fauria/vsftpd
    environment:
      FTP_USER: ftptest
      FTP_PASS: ftptest
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    ports:
      - "20:20"
      - "21:21"
      - 21100-21110:21100-21110
    volumes:
      - ./ftp:/home/vsftpd