version: "3.3"

services:
  mongodb:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abcd1234
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: --smallfiles