version: "3.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: logstash:6.5.4
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 5000:5000
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./data/logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:6.5.4
    ports:
      - 5601:5601
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge